---
# tasks file for mapr-httpfs
- name: Install Packages
  apt: pkg={{ item }} state=latest 
  with_items:
    - mapr-httpfs
  when: ansible_distribution == 'Ubuntu' and hue_version == '3.5'

- name: Install Packages
  yum: pkg={{ item }} state=latest 
  with_items:
    - mapr-httpfs
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Check and register httpfs version
  shell: ls /opt/mapr/httpfs | grep httpfs- | sort | tail -n1
  register: httpfs_version

- name: Install httpfs-site.xml
  copy: src=httpfs-site.xml dest=/opt/mapr/httpfs/{{httpfs_version.stdout}}/etc/hadoop/httpfs-site.xml
