---
# tasks file for mapr-httpfs
- name: Install Packages
  apt: pkg={{ item }} state=present 
  with_items:
    - mapr-httpfs
  when: ansible_distribution == 'Ubuntu' and hue_version == '3.5'

- name: Install Packages
  yum: pkg={{ item }} state=present 
  with_items:
    - mapr-httpfs
  when: ansible_distribution in ('CentOS', 'Red Hat Enterprise Linux', 'Amazon')

- name: Check and register httpfs version
  shell: ls /opt/mapr/httpfs | grep httpfs- | sort | tail -n1
  register: httpfs_version

- name: configure httpfs proxy user (hosts)
  hadoop_properties:
    file: /opt/mapr/httpfs/{{httpfs_version.stdout}}/etc/hadoop/httpfs-site.xml
    name: httpfs.proxyuser.mapr.hosts
    value: '*'

- name: configure httpfs proxy user (groups)
  hadoop_properties:
    file: /opt/mapr/httpfs/{{httpfs_version.stdout}}/etc/hadoop/httpfs-site.xml
    name: httpfs.proxyuser.mapr.groups
    value: '*'

#- name: Install httpfs-site.xml
#  copy: src=httpfs-site.xml dest=/opt/mapr/httpfs/{{httpfs_version.stdout}}/etc/hadoop/httpfs-site.xml
