---
# file hue.yml

- hosts: hue;jobtracker
  roles:
    - common
    - python-lxml

- hosts: hue
  roles:
    - mapr-httpfs
    - mapr-oozie
    - mapr-pig
    - hue

- hosts: jobtracker
  roles:
    - jobtracker-plugin
  tasks:
    - name: Copy Hue plugins to Jobtrackers
      copy: src=/tmp/hue-plugins-3.6.0-mapr.jar dest="{{mapr_hadoop1_path}}/lib"

#- hosts: cluster
#  gather_facts : no
#  tasks:
#    - name: Bringing up all services
#      shell: echo " "
#      notify: 
#        - Restart Jobtracker
#        - Pause after Jobtracker
#        - Start Oozie
#        #- Pause before Beeswax
#        #- Start Beeswax
#        - Pause before Hue
#        - Start Hue
