---
# file hue.yml

- hosts: all
  sudo: yes
  roles:
    - common
    - hue

- hosts: jobtracker_nodes
  sudo: yes
  tasks:
    - include: roles/hue/tasks/plugins.yml

- hosts: all
  gather_facts : no
  sudo: yes
  roles:
    - common
  tasks:
    - include: roles/hue/tasks/services.yml
