---
# file hue.yml

- hosts: hue;jobtracker
  roles:
    - common
    - python-lxml

- hosts: hue
  roles:
    - mapr-httpfs
    - mapr-oozie
    - mapr-pig
    - hue
  tasks:
    - name: check whether tables volume exists
      shell: maprcli volume list -columns volumename | grep tables
      register: tables_volume
      failed_when: tables_volume.rc not in (0,1)

    - name: create a volume for mapr tables
      command: maprcli volume create -name tables -path /tables
      when: tables_volume.rc == 1

- hosts: jobtracker
  roles:
    - jobtracker-plugin
  tasks:
    - name: Copy Hue plugins to Jobtrackers
      copy: src=/tmp/hue-plugins-3.6.0-mapr.jar dest="{{mapr_hadoop1_path}}/lib"
