---
# file hue.yml

- hosts: hiveserver
  sudo: yes
  roles:
    - common
    - mapr-httpfs
    - mapr-oozie

- hosts: hiveserver;jobtracker
  sudo: yes
  roles:
    - hue

- hosts: jobtracker
#- hosts: all
  gather_facts: no
  sudo: yes
  tasks:
    - include: roles/hue/tasks/plugins.yml

- hosts: cluster
  gather_facts : no
  sudo: yes
  roles:
    - common
  tasks:
   - include: roles/hue/tasks/services.yml
