---
# file: roles/common/tasks/main.yml

- name: Install Packages
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - mysql-server
  when: ansible_distribution == 'Ubuntu'

- name: Install Packages
  yum: pkg={{ item }} state=latest force=yes
  with_items:
    - mysql-server
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: configure mysql.conf
  lineinfile: dest=/etc/mysql/my.cnf
    state=present
    regexp='^bind-address'
    line='bind-address = {{ansible_eth1.ipv4.address}}'

- name: Start mysql service
  service: name=mysql state=restarted

- name: Setup mysql root password
  command: mysqladmin -u root password {{mysql_root_password}}

- name: Install my.conf
  template: src=my.cnf dest=~/.my.cnf
