---
# file: roles/common/handlers/main.yml
# In a secure cluster, this will fail unless you've done
# maprlogin already.
- name: Restart ntp
  service: name=ntp state=restarted

- name: Restart Jobtracker
  shell: sudo -u mapr maprcli node services -jobtracker restart -filter csvc==jobtracker

- name: Start Oozie
  shell: sudo -u mapr maprcli node services -name oozie -action start -filter csvc==oozie

- name: Stop Oozie
  shell: sudo -u mapr maprcli node services -name oozie -action stop -filter csvc==oozie

- name: Restart Oozie
  shell: sudo -u mapr maprcli node services -name oozie -action restart -filter csvc==oozie

- name: Start Hue
  shell: sudo -u mapr maprcli node services -name hue -action start -filter csvc==hue

- name: Stop Hue
  shell: sudo -u mapr maprcli node services -name hue -action stop -filter csvc==hue

- name: Restart Hue
  shell: sudo -u mapr maprcli node services -name hue -action restart -filter csvc==hue

#- name: Start Beeswax
#  shell: maprcli node services -name beeswax -action start -filter csvc==beeswax

#- name: Stop Beeswax
#  shell: maprcli node services -name beeswax -action stop -filter csvc==beeswax

#- name: Restart Beeswax
#  shell: maprcli node services -name beeswax -action restart -filter csvc==beeswax

- name: Pause after Jobtracker
  pause: seconds=10

- name: Pause after Oozie
  pause: seconds=10

- name: Pause before Beeswax
  pause: seconds=10

- name: Pause before Hue
  pause: seconds=10
