---
# tasks file for oozie
- name: install oozie (Ubuntu)
  apt: pkg={{ item }} state=present
  with_items:
    - mapr-oozie
  when: ansible_distribution == 'Ubuntu' 
  notify: reconfigure roles

- name: install oozie (RedHat)
  yum: pkg={{ item }} state=present
  with_items:
    - mapr-oozie
  when: ansible_distribution in ('CentOS','RedHat','Amazon')
  notify: reconfigure roles

- name: Check and register Oozie version
  shell: ls /opt/mapr/oozie | grep oozie- | sort | tail -n1
  register: oozie_version

- name: update oozie-site.xml for impersonation (hosts)
  hadoop_properties:
    file: "/opt/mapr/oozie/{{oozie_version.stdout}}/conf/oozie-site.xml"
    name: 'oozie.service.ProxyUserService.proxyuser.mapr.hosts'
    value: '*'
  register: proxyuser_hosts
  notify: reconfigure roles

- debug: var=proxyuser_hosts

- name: update oozie-site.xml for impersonation (groups)
  hadoop_properties:
    file: "/opt/mapr/oozie/{{oozie_version.stdout}}/conf/oozie-site.xml"
    name: 'oozie.service.ProxyUserService.proxyuser.mapr.groups'
    value: '*'
  notify: reconfigure roles

### Install Oozie files

- name: make the oozie share lib directory
  file: state=directory path="/mapr/{{cluster_name.stdout}}/oozie/share/lib" mode=0755 owner=mapr group=mapr
  notify: reconfigure roles

- name: Decompress Oozie examples
  shell: tar zxf /opt/mapr/oozie/{{oozie_version.stdout}}/oozie-examples.tar.gz -C /mapr/{{cluster_name.stdout}}/oozie/share/lib
  notify: reconfigure roles

- name: Decompress Oozie shared libs
  shell: tar zxf /opt/mapr/oozie/{{oozie_version.stdout}}/oozie-sharelib*.tar.gz -C /mapr/{{cluster_name.stdout}}/oozie/share/lib
  notify: reconfigure roles
