---
# file: roles/common/tasks/main.yml

- name: Find all Jobtrackers in the cluster
  shell: maprcli node list -columns svc | grep jobtracker | awk {'print $2'}
  register: jobtrackers

- debug: var=jobtrackers

- name: Create an array of Jobtrackers to pass as vars
  shell: echo {{jobtrackers.stdout}} | sed ':a;N;$!ba;s/\n/ /g'
  register: jobtracker_array

- debug: var=jobtracker_array

- name: Create Jobtracker host group
  local_action: add_host hostname={{item}} groupname=jobtracker_nodes
  with_items: "jobtrackers.stdout"
