---
- name: configure jobtracker (mr1) thrift address
  hadoop_properties:
    file: "{{mapr_hadoop1_path}}/conf/mapred-site.xml"
    name: 'jobtracker.thrift.address'
    value: '0.0.0.0:9290'

#- name: configure jobtracker (mr2) thrift address
#  hadoop_properties:
#    file: "{{mapr_hadoop2_path}}/etc/hadoop/mapred-site.xml"
#    name: 'jobtracker.thrift.address'
#    value: '0.0.0.0:9290'

- name: configure jobtracker plugins (mr1)
  hadoop_properties:
    file: "{{mapr_hadoop1_path}}/conf/mapred-site.xml"
    name: 'mapred.jobtracker.plugins'
    value: 'org.apache.hadoop.thriftfs.ThriftJobTrackerPlugin'
      
#- name: configure jobtracker plugins (mr2)
#  hadoop_properties:
#    file: "{{mapr_hadoop2_path}}/etc/hadoop/mapred-site.xml"
#    name: 'mapred.jobtracker.plugins'
#    value: 'org.apache.hadoop.thriftfs.ThriftJobTrackerPlugin'

- name: enable impersonation in Hue (hosts) (mr1)
  hadoop_properties:
    file: "{{mapr_hadoop1_path}}/conf/core-site.xml"
    name: 'hadoop.proxyuser.mapr.hosts'
    value: '*'

- name: enable impersonation in Hue (groups) (mr1)
  hadoop_properties:
    file: "{{mapr_hadoop1_path}}/conf/core-site.xml"
    name: 'hadoop.proxyuser.mapr.groups'
    value: '*'

#- name: enable impersonation in Hue (hosts) (mr2)
#  hadoop_properties:
#    file: "{{mapr_hadoop2_path}}/etc/hadoop/core-site.xml"
#    name: 'hadoop.proxyuser.mapr.hosts'
#    value: '*'

#- name: enable impersonation in Hue (groups) (mr2)
#  hadoop_properties:
#    file: "{{mapr_hadoop2_path}}/etc/hadoop/core-site.xml"
#    name: 'hadoop.proxyuser.mapr.groups'
#    value: '*'
