---
# file: roles/common/tasks/check_versions.yml

- name: Check and register Hue version
  shell: ls /opt/mapr/hue | grep hue- | sort | tail -n1
  register: hue_version

- name: Check and register Hive version
  shell: ls /opt/mapr/hive | grep hive- | sort | tail -n1
  register: hive_version

- name: Check and register hadoop1 version
  shell: ls -d /opt/mapr/hadoop-0* | grep hadoop- | sort | tail -n1
  register: hadoop1_version

- name: Check and register hadoop2 version
  shell: ls -d /opt/mapr/hadoop-2* | grep hadoop- | sort | tail -n1
  register: hadoop2_version
