---
# file: roles/common/tasks/main.yml

- include: prereqs.yml

- name: Install hue and hbase-thrift gateway
  apt: pkg={{ item }} state=present 
  with_items:
    - mapr-hue
    - mapr-hbasethrift
  when: ansible_distribution == 'Ubuntu'
  notify: reconfigure roles

- name: Install hue and hbase-thrift gateway
  yum: pkg={{ item }} state=present 
  with_items:
    - mapr-hue
    - mapr-hbasethrift
  when: ansible_distribution in ('CentOS', 'RedHat', 'Amazon')
  notify: reconfigure roles

- name: configure HBase to MapR DB table mapping 
  hadoop_properties: name=hbase.table.namespace.mappings value="*:/tables" file={{mapr_hadoop2_path}}/etc/hadoop/core-site.xml

- name: register the hue path
  shell: ls -d /opt/mapr/hue/hue-* | tail -1
  register: hue_path
  failed_when: hue_path.rc != 0

- name: set a fact about the hue_path
  set_fact:
    mapr_hue_path: '{{hue_path.stdout}}'

- name: generate hue_secret_key from /dev/urandom
  shell: dd if=/dev/urandom count=1024 | sha512sum | awk '{ print $1}'
  register: hue_secret_key

- name: install hue.ini
  template: src=hue-3.6.ini.j2 dest=/opt/mapr/hue/hue-3.6.0/desktop/conf/hue.ini mode=0644 owner=mapr group=mapr backup=yes
  notify: restart hue

- name: fetch the hue plugins
  sudo: no
  fetch: src={{mapr_hue_path}}/desktop/libs/hadoop/java-lib/hue-plugins-3.6.0-mapr.jar dest=/tmp flat=true validate_md5=false
  register: fetch
