---
# file: roles/common/tasks/main.yml

- name: add third-party repo for python-2.6
  apt_repository: repo='ppa:fkrull/deadsnakes'

- name: update all packages to the latest version
  apt: update_cache=yes 

- name: install Packages
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - python-mysqldb
    - python-software-properties
    - python2.6
    - libssl0.9.8
    - libxslt1.1
    - libsasl2-modules-gssapi-mit
    - mapr-hue
    - mapr-httpfs
    - mapr-hive
    - mapr-hivemetastore
    - mapr-oozie
    - mysql-server

- name: download mysql java connector
  command: wget -O /tmp/mysql-connector.tar.gz http://www.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.18.tar.gz/from/http://mysql.he.net/%8Chttp://mysql.he.net/

- name: configure mysql.conf
  lineinfile: dest=/etc/mysql/my.cnf
    state=present
    regexp='^bind-address'
    line='bind-address = {{ ansible_eth1.ipv4.address }}'

- name: start mysql service
  service: name=mysql state=started

- name: setup mysql root password
  command: mysqladmin -u root password mapr

- name: copy my.conf
  copy: src=my.cnf dest=~/.my.cnf

- name: create hive metastore db
  mysql_db: name=hive_11 state=present

- name: create hive metastore db user
  mysql_user: name=mapr password=mapr priv=hive_11.*:ALL state=present host=%

- name: copy hue plugins to job trackers
  shell: cp /opt/mapr/hue/hue*/desktop/libs/hadoop/java-lib/hue-plugins-*.jar /opt/mapr/hadoop/hadoop*/lib/

- name: configure webhdfs_url
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^webhdfs_url'
    line='webhdfs_url=http://{{ ansible_eth1.ipv4.address }}:14000/webhdfs/v1'

- name: configure jobtracker_host
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^jobtracker_host'
    line='jobtracker_host={{ ansible_eth1.ipv4.address }}'

- name: configure oozie_url
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^oozie_url'
    line='oozie_url={{ ansible_eth1.ipv4.address }}:11000/oozie'

- name: configure beeswax_url
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^beeswax_server_host'
    line='beeswax_server_host={{ ansible_eth1.ipv4.address }}'

- name: configure beeswax_meta_server_host
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^beeswax_meta_server_host'
    line='beeswax_meta_server_host={{ ansible_eth1.ipv4.address }}'

- name: configure hive home directory
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^hive_home_dir'
    line='hive_home_dir=/opt/mapr/hive/hive-0.12'

- name: configure hive conf directory
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^hive_conf_dir'
    line='hive_conf_dir=/opt/mapr/hive/hive-0.12/conf'

- name: copy hive-site.xml
  template: src=hive-site.xml.j2 dest=/opt/mapr/hive/hive-0.12/conf/hive-site.xml 

- name: copy mapred-site.xml
  copy: src=mapred-site.xml dest=/opt/mapr/hadoop/hadoop-0.20.2/conf/mapred-site.xml 

- name: copy core-site.xml
  copy: src=core-site.xml dest=/opt/mapr/hadoop/hadoop-0.20.2/conf/core-site.xml 

- name: copy oozie-site.xml
  copy: src=oozie-site.xml dest=/opt/mapr/oozie/oozie-4.0.0/oozie-site.xml 

- name: copy httpfs-site.xml
  copy: src=httpfs-site.xml dest=/opt/mapr/httpfs/httpfs-1.0/etc/hadoop/httpfs-site.xml

- name: decompress oozie examples
  shell: tar zxf /opt/mapr/oozie/oozie*/oozie-examples.tar.gz --strip-components 1  -C /mapr/{{ cluster_name }}/oozie/share/lib

- name: decompress oozie shared libs
  shell: tar zxf /opt/mapr/oozie/oozie*/oozie-sharelib-4.0.0-mapr-1403.tar.gz -C /mapr/{{ cluster_name }}/oozie

- name: set oozie file permissions
  file: path=/mapr/my.cluster.com/oozie mode=0777 recurse=yes

- name: install mysql java connector
  shell: cp /tmp/mysql-connector-java-5.1.18/mysql-connector-java-5.1.18-bin.jar /opt/mapr/hive/hive*/lib

- name: restart jobtracker
  shell: maprcli node services -jobtracker restart -nodes {{ jobtracker_nodes }}

- name: stop oozie
  shell: maprcli node services -name oozie -action stop -nodes {{ jobtracker_nodes }}

- name: start oozie
  shell: maprcli node services -name oozie -action start -nodes {{ jobtracker_nodes }}

- name: start hue
  shell: maprcli node services -name hue -action start -nodes {{ jobtracker_nodes }}

- name: start beeswax
  shell: maprcli node services -name hue -action start -nodes {{ jobtracker_nodes }}
