---
# file: roles/common/tasks/main.yml

- include: prereqs.yml

- name: install hive
  apt: pkg={{item}} state=present
  with_items:
    - mapr-hive
  when: ansible_distribution == 'Ubuntu' and hue_version == '3.5'
  register: mapr_hive

- name: install hivemetastore
  apt: pkg={{item}} state=present
  with_items:
    - mapr-hivemetastore
  when: ansible_distribution == 'Ubuntu' and hue_version == '3.5'
  register: mapr_hivemetastore

- name: Install Packages
  apt: pkg={{ item }} state=present 
  with_items:
    - mapr-hue
  when: ansible_distribution == 'Ubuntu' and hue_version == '3.5'

- name: Install Packages
  yum: pkg={{ item }} state=present 
  with_items:
    - mapr-hue
    - mapr-hive
    - mapr-hivemetastore
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: check_versions.yml
#- include: mysql.yml

### Install configs

- name: Install hue.ini
  template: src=hue-2.5.ini.j2 dest=/opt/mapr/hue/{{hue_version.stdout}}/desktop/conf/hue.ini 
  when: ansible_distribution == 'Ubuntu' and hue_version == '2.5'

- name: install hive-site.xml if we just installed hive
  template: src=hive-site.xml.j2 dest=/opt/mapr/hive/{{hive_version.stdout}}/conf/hive-site.xml 
  when: mapr_hive.changed

- name: Install mapred-site.xml
  copy: src=mapred-site.xml dest=/opt/mapr/hadoop/{{hadoop_version.stdout}}/conf/mapred-site.xml 

- name: Install core-site.xml
  copy: src=core-site.xml dest=/opt/mapr/hadoop/{{hadoop_version.stdout}}/conf/core-site.xml 
