---
# file: roles/common/tasks/main.yml

- name: install Packages
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - mapr-hue
    - mapr-httpfs
    - mapr-hive
    - mapr-hivemetastore
    - mapr-oozie
    - mysql-server
  when: ansible_distribution == 'Ubuntu'

- name: Install Packages
  yum: pkg={{ item }} state=latest force=yes
  with_items:
    - mapr-hue
    - mapr-httpfs
    - mapr-hive
    - mapr-hivemetastore
    - mapr-oozie
    - mysql-server
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: configure mysql.conf
  lineinfile: dest=/etc/mysql/my.cnf
    state=present
    regexp='^bind-address'
    line='bind-address = {{ansible_eth1.ipv4.address}}'

- name: start mysql service
  service: name=mysql state=restarted

- name: setup mysql root password
  command: mysqladmin -u root password mapr

- name: copy my.conf
  copy: src=my.cnf dest=~/.my.cnf

- name: create hive metastore db
  mysql_db: name=hive_11 state=present

- name: create hive metastore db user
  mysql_user: name=mapr password=mapr priv=hive_11.*:ALL state=present host=%

- name: copy hue plugins to job trackers
  shell: cp /opt/mapr/hue/hue*/desktop/libs/hadoop/java-lib/hue-plugins-*.jar /opt/mapr/hadoop/hadoop*/lib/

- name: configure webhdfs_url
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^webhdfs_url'
    line='webhdfs_url=http://{{ansible_eth1.ipv4.address}}:14000/webhdfs/v1'

- name: configure jobtracker_host
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^jobtracker_host'
    line='jobtracker_host={{ansible_eth1.ipv4.address}}'

- name: configure oozie_url
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^oozie_url'
    line='oozie_url={{ansible_eth1.ipv4.address}}:11000/oozie'

- name: configure beeswax_url
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^beeswax_server_host'
    line='beeswax_server_host={{ansible_eth1.ipv4.address}}'

- name: configure beeswax_meta_server_host
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^beeswax_meta_server_host'
    line='beeswax_meta_server_host={{ansible_eth1.ipv4.address}}'

- name: configure hive home directory
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^  hive_home_dir' backrefs=yes
    line='hive_home_dir=/opt/mapr/hive/hive-0.12'

- name: configure hive conf directory
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^  hive_conf_dir' backrefs=yes
    line='hive_conf_dir=/opt/mapr/hive/hive-0.12/conf'

- name: configure hive home directory
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^hive_home_dir' backrefs=yes
    line='hive_home_dir=/opt/mapr/hive/hive-0.12'

- name: configure hive conf directory
  lineinfile: dest=/opt/mapr/hue/hue-2.5.0/desktop/conf/hue.ini
    state=present
    regexp='^hive_conf_dir' backrefs=yes
    line='hive_conf_dir=/opt/mapr/hive/hive-0.12/conf'

- name: copy hive-site.xml
  template: src=hive-site.xml.j2 dest=/opt/mapr/hive/hive-0.12/conf/hive-site.xml 

- name: copy mapred-site.xml
  copy: src=mapred-site.xml dest=/opt/mapr/hadoop/hadoop-0.20.2/conf/mapred-site.xml 

- name: copy core-site.xml
  copy: src=core-site.xml dest=/opt/mapr/hadoop/hadoop-0.20.2/conf/core-site.xml 

- name: copy oozie-site.xml
  copy: src=oozie-site.xml dest=/opt/mapr/oozie/oozie-4.0.0/oozie-site.xml 

- name: copy httpfs-site.xml
  copy: src=httpfs-site.xml dest=/opt/mapr/httpfs/httpfs-1.0/etc/hadoop/httpfs-site.xml

- name: Create oozie shared lib directory
  file: path=/mapr/{{cluster_name}}/oozie/share/lib state=directory

- name: decompress oozie examples
  shell: tar zxf /opt/mapr/oozie/oozie*/oozie-examples.tar.gz --strip-components 1 -C /mapr/{{cluster_name}}/oozie/share/lib

- name: decompress oozie shared libs
  shell: tar zxf /opt/mapr/oozie/oozie*/oozie-sharelib-4.0.0-mapr-1403.tar.gz -C /mapr/{{cluster_name}}/oozie

- name: set oozie file permissions
  file: path=/mapr/{{cluster_name}}/oozie mode=0777 recurse=yes

- name: install mysql java connector
  copy: src=mysql-connector-java-5.1.18-bin.jar dest=/opt/mapr/hive/hive-0.12/lib

- name: restart jobtracker
  shell: maprcli node services -jobtracker restart -nodes {{jobtracker_nodes}}

- name: Pausing for 15 seconds to allow jobtracker to fire up
  pause: seconds=15

- name: Stop oozie
  shell: maprcli node services -name oozie -action stop -nodes {{jobtracker_nodes}}

- name: Start oozie
  shell: maprcli node services -name oozie -action start -nodes {{jobtracker_nodes}}

- name: Start hue
  shell: maprcli node services -name hue -action start -nodes {{jobtracker_nodes}}

- name: Start beeswax
  shell: maprcli node services -name hue -action start -nodes {{jobtracker_nodes}}
