---
# file: roles/hue/tasks/mysql.yml
#
- name: Create Hive metastore db
  mysql_db: login_host={{mysql_host}} name={{mysql_hive_metastore_db_name}} state=present

- name: Create Hive metastore db user
  mysql_user: login_host={{mysql_host}} name={{mysql_user}} password={{mysql_password}} priv=hive_11.*:ALL state=present host=%

### Install the MySQL Java connector no-one tells you about

- name: Install mysql java connector
  copy: src=mysql-connector-java-5.1.18-bin.jar dest=/opt/mapr/hive/{{hive_version.stdout}}/lib
